#! /bin/sh


bspc monitor DP-3 -d 1 2 3 4 5 6
bspc monitor eDP-1 -d 7
# bspc wm -0 DP-3 eDP-1
xsetroot -cursor_name left_ptr
 
bspc config border_width         1
bspc config window_gap          5
bspc config top_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

bspc config split_ratio          0.60
bspc config focus_follows_pointer true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
sxhkd & $HOME/.config/polybar/launch.sh && compton -b && sb-monitor && nitrogen --restore 
